# Site settings
baseURL = "https://gohugo.xyz/"
languageCode = "en-us"
title = "GO HUGO"
theme = "hugo-simpledoc-theme"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

# Top menu
[[menu.top]]
    name = "Hugo - A Fast and Flexible Website Generator"
    weight = 10
    url = "http://gohugo.io/"

# Site parameters
[params]

    # Meta
    description = "HUGO é™æ€ç«™ç‚¹ç”Ÿæˆå™¨äº¤æµã€‚ä½†æˆ‘ä»¬èŠå¾—ä¸æ­¢æ˜¯æŠ€æœ¯ã€‚The worldâ€™s fastest framework for building websites."
    author = "Julian"
    keywords = "hugo, documentation, hugo theme, hugo simple documentation theme"
    
    # Header
    # If not set, site title and meta description will be shown.
    # You may use markdown here
    headerTitle = "GO HUGO"
    headerDescription = "HUGO é™æ€ç«™ç‚¹ç”Ÿæˆå™¨äº¤æµã€‚ä½†æˆ‘ä»¬èŠå¾—ä¸æ­¢æ˜¯æŠ€æœ¯ã€‚The worldâ€™s fastest framework for building websites."
    
    # Back-to-top button name
    bttButton = "å›åˆ°é¡¶éƒ¨ğŸ‘†"